'use strict';
const fs = require('node:fs');
const path = require('node:path');
const names = require('./manifest.json');
const head = '/* CELL4 ARC engine - generated by node c4-arc/build.js. Edit c4-arc/src/. */\n(function (root) {\n"use strict";\n\n';
const body = names.map(n => fs.readFileSync(path.join(__dirname, 'src', n), 'utf8')).join('');
const out = head + body + "})(typeof window !== 'undefined' ? window : globalThis);\n";
const dest = process.argv[2] ? path.resolve(process.argv[2]) : path.join(__dirname, '..', 'c4-arc-engine.js');   /* optional: build elsewhere so a running bench keeps its engine */
fs.writeFileSync(dest, out);
console.log(`Built ${names.length} modules (${Buffer.byteLength(out)} bytes)`);
