/* Mine library concepts (DreamCoder-style abstraction) from solved programs.
 *
 *   node tools/arc-library.js [--write] [--out FILE] [--exclude KEY,...]
 *
 * Source: the demonstration-exact entity programs the search finds on the
 * FIRST HALF of the development corpus (no test output is read). A candidate
 * concept is a pair of generative operators applied by ONE rule (same
 * selection predicate, same colour expression) somewhere in those programs.
 * It is accepted only if
 *   support    it occurs in >= 2 distinct source tasks (not a task instance)
 *   MDL        the bits it saves across its uses exceed the bits of its own
 *              definition (a library entry pays for itself)
 * and then VALIDATED on held-out real tasks (second half of the corpus):
 * matched-execution top-1 with and without the library (tools/arc-sls.js
 * --half 2 after --write). --exclude drops candidates by key
 * (leave-family-out: remove a concept family, test whether composition of
 * the remaining primitives still recovers its tasks).
 */
'use strict';
const fs = require('fs'), path = require('path');
const D = require('./arc-dream-lib.js'), E = D.E;
const args = process.argv.slice(2);
const arg = (k, d) => { const i = args.indexOf('--' + k); return i < 0 ? d : args[i + 1]; };
const exclude = arg('exclude') ? arg('exclude').split(',') : [];
const corpusFile = path.join(__dirname, '..', 'c4-arc-tasks.js');
const all = D.inputGroups(corpusFile, 'arc1_');
const firstHalf = new Set(all.slice(0, Math.floor(all.length / 2)).map(g => g.id));
const T = require(corpusFile);
const grid = s => s.split('|').map(r => [...r].map(Number));
const pairs = s => s.split(';').map(p => { const [x, y] = p.split('>'); return [grid(x), grid(y)]; });
const cand = new Map();
let tasksWithProgs = 0;
for (const row of T) {
  if (!firstHalf.has(row[0])) continue;
  const tr = pairs(row[1]);
  if (!tr.every(([x, y]) => x.length === y.length && x[0].length === y[0].length)) continue;
  const ctx = new E.Ctx(tr, pairs(row[2]).map(p => p[0]), null);
  let progs = [];
  try { progs = E.SKETCH.synthesize(ctx, Date.now() + 3000, {}); } catch (e) { continue; }
  if (!progs.length) continue;
  tasksWithProgs++;
  const seenHere = new Set();
  for (const p of progs) {
    const g = p.grow || [];
    for (let i = 0; i < g.length; i++) for (let j = i + 1; j < g.length; j++) {
      const A = g[i], B = g[j];
      if (A.p.k !== B.p.k) continue;                       /* one rule selects both */
      if ((A.g.c ? A.g.c.k : '#') !== (B.g.c ? B.g.c.k : '#')) continue;
      const key = A.g.op.key + '+' + B.g.op.key;
      if (exclude.includes(key)) continue;
      const c = cand.get(key) || { a: A.g.op.key, b: B.g.op.key, tasks: new Set(), uses: 0, saved: 0, defBits: A.g.op.b + B.g.op.b };
      c.uses++;
      /* re-expressed with the concept: one rule instead of two */
      c.saved += 1 + A.p.b + (A.g.c ? A.g.c.b : 0) + (Math.min(A.g.op.b, B.g.op.b) - 1);
      if (!seenHere.has(key)) { c.tasks.add(row[0]); seenHere.add(key); }
      cand.set(key, c);
    }
  }
}
const scored = [...cand.values()].map(c => ({ a: c.a, b: c.b, support: c.tasks.size, uses: c.uses,
  gain: +(c.saved / Math.max(1, c.uses) * c.tasks.size - c.defBits).toFixed(2) }))
  .sort((x, y) => y.gain - x.gain);
const accepted = scored.filter(c => c.support >= 2 && c.gain > 0).slice(0, 8);
const report = { source_tasks_with_programs: tasksWithProgs, candidates: scored.length, accepted, rejected_top: scored.filter(c => !accepted.includes(c)).slice(0, 8), exclude };
console.log(JSON.stringify(report, null, 1));
if (arg('out')) fs.writeFileSync(arg('out'), JSON.stringify(report, null, 2));
if (args.includes('--write')) {
  const body = '/* ===== src/62b-concepts.js ===== */\n/* GENERATED by tools/arc-library.js from demonstration-exact programs on the\n * first half of the development corpus; accepted by support >= 2 tasks and\n * positive MDL gain. Each concept is two generative operators of one rule. */\nvar CONCEPT_DEFS = ' +
    JSON.stringify(accepted.map(c => ({ a: c.a, b: c.b, support: c.support, gain: c.gain }))) + ';\nCONCEPT_DEFS.forEach(function (d) { GEN.addFused(d); });\n';
  fs.writeFileSync(path.join(__dirname, '..', 'c4-arc', 'src', '62b-concepts.js'), body);
  console.log('wrote c4-arc/src/62b-concepts.js (' + accepted.length + ' concepts)');
}
